[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.134", features = ["derive"] }
dirs = "4.0.0"
anyhow = "1.0.53"
which = "4.2.2"
log = "0.4.14"
simplelog = "0.11.2"
chrono = "0.4.19"
